import {
  LayoutDashboard,
  Hammer,
  PenTool,
  FileQuestion,
  Calculator,
  Briefcase,
  Receipt,
  Landmark,
  CheckSquare,
  Users,
  MessageCircle,
  UserCircle,
  DollarSign,
} from "lucide-react";
import type { JSX } from "react";

export interface NavItem {
  label: string;
  to: string;
  icon: JSX.Element;
  roles: string[];
}

export const navItems: NavItem[] = [
  {
    label: "Dashboard",
    to: "/dashboard",
    icon: <LayoutDashboard />,
    roles: [
      "admin",
      "staff",
      "department-manager",
      "estimation_head",
      "deputy_manager",
      "project-manager",
      "client",
      "client_admin",
      "system-admin",
      "user",
      "estimator",
      "sales",
      "sales_manager",
    ],
  },
  {
    label: "Fabricator",
    to: "fabricator",
    icon: <Hammer />,
    roles: [
      "admin",
      "department-manager",
      "deputy_manager",
      "project-manager",
      "system-admin",
      "user",
      "estimator",
      "sales_manager",
      "sales",
    ],
  },
  {
    label: "Connection Designer",
    to: "connection-designer",
    icon: <PenTool />,
    roles: ["admin", "department-manager", "deputy_manager"],
  },
  // {
  //   label: "Connection Designing Quotation",
  //   to: "connection-designing-quotation",
  //   icon: <FactoryIcon />,
  //   roles: [
  //     "admin",
  //     "department-manager",
  //     "connection_designer_engineer",
  //     "deputy_manager",
  //   ],
  // },
  {
    label: "RFQ",
    to: "rfq",
    icon: <FileQuestion />,
    roles: [
      "admin",
      "sales_manager",
      "deputy_manager",
      "client_admin",
      "client",
      "estimator",
      "sales",
    ],
  },
  {
    label: "Estimations",
    to: "estimation",
    icon: <Calculator />,
    roles: [
      "admin",
      "sales_manager",
      "estimation_head",
      "department-manager",
      "deputy_manager",
      "user",
    ],
  },
  {
    label: "Projects",
    to: "projects",
    icon: <Briefcase />,
    roles: [
      "admin",
      "dept_manager",
      "deputy_manager",
      "team_lead",
      "staff",
      "sales_manager",
      "client_admin",
      "connection_designer_engineer",
      "client",
      "project_manager",
      "user",
      "human-resource",
    ],
  },
  {
    label: "Invoices",
    to: "invoices",
    icon: <Receipt />,
    roles: ["admin", "deputy_manager", "client_admin", "pmo", "client"],
  },
  {
    label: "Accounts",
    to: "accounts",
    icon: <Landmark />,
    roles: ["admin", "deputy_manager", "pmo"],
  },
  {
    label: "Tasks",
    to: "tasks",
    icon: <CheckSquare />,
    roles: [
      "admin",
      "staff",
      "department-manager",
      "deputy_manager",
      "project-manager",
      "user",
      "system-admin",
      "human-resource",
    ],
  },
  {
    label: "Sales",
    to: "sales",
    icon: <DollarSign />,
    roles: [
      "admin",
      "sales",
      "sales_manager",
      "department-manager",
      "deputy_manager",
      "system-admin",
    ],
  },
  {
    label: "Manage Team",
    to: "manage-team",
    icon: <Users />,
    roles: [
      "admin",
      "department-manager",
      "project-manager",
      "deputy_manager",
      "user",
      "human-resource",
    ],
  },
  {
    label: "Chats",
    to: "chats",
    icon: <MessageCircle />,
    roles: [
      "admin",
      "staff",
      "department-manager",
      "project-manager",
      "estimation_head",
      "deputy_manager",
      "user",
      "human-resource",
    ],
  },
  {
    label: "Profile",
    to: "profile",
    icon: <UserCircle />,
    roles: [
      "admin",
      "connection_designer_engineer",
      "user",
      "estimation_head",
      "staff",
      "client",
      "connection_designer_engineer",
      "estimator",
      "sales",
      "sales_manager",
      "dept_manager",
      "client_admin",
      "deputy_manager",
      "project_manager",
      "system_admin",
      "human_resource",
    ],
  },
  
];
